### ISSUE TITLE
图片删除功能

### ISSUE THREAD

**Issue by sim1233** [Edge-coordinates/Waterfall_picture_viewer#5]
能否增加一下图片的右键删除功能 或者在查看单一图片时可以按del键删除

**Comment by Edge-coordinates** [comment]
> 能否增加一下图片的右键删除功能 或者在查看单一图片时可以按del键删除

嗯嗯，如果有时间就看看~qwq

**Comment by Edge-coordinates** [comment]
The version has been updated now~
