### ISSUE TITLE
希望读取webp格式

### ISSUE THREAD

**Issue by jamesfu1978** [Edge-coordinates/Waterfall_picture_viewer#6]
软件没读取webp格式的文件，目前从网站上下载的图片有部分是webp格式的，这样还需要再转png或jpg才行(或者直接改后缀名)。

还更新的话，希望能增加webp的读取吧，这软件临时看图还是挺好用的。

（ico的也没读取，虽然没必要）

**Comment by yyyanyy** [comment]
还有jxl希望，

**Comment by Edge-coordinates** [comment]
好的，最近在研究新的 UI 框架，打算进行 彻底重构，尽量支持

**Comment by Edge-coordinates** [comment]
新版本已添加~

**Comment by Edge-coordinates** [comment]
新版本已添加~
