### ISSUE TITLE
无法载入图片

### ISSUE THREAD

**Issue by ChenDY2233** [Edge-coordinates/Waterfall_picture_viewer#8]
**Describe the bug**
**拖入文件夹** 或者 **从对话框选择文件夹** 打开，都无法载入，界面上无提示
文件夹名称 `yuuhui玉汇 - 圣女の史莱姆修行计划 [106P1.53GB]`

**Screenshots**
console 报错如下
![image](https://github.com/Edge-coordinates/Waterfall_picture_viewer/assets/39426660/0f90bdf4-a412-422a-9882-c00390846bda)

图片基本信息如下
![image](https://github.com/Edge-coordinates/Waterfall_picture_viewer/assets/39426660/33f289dc-13e5-48b5-935e-04f85f787456)

**Additional context**

**Comment by Edge-coordinates** [comment]
> **Describe the bug** **拖入文件夹** 或者 **从对话框选择文件夹** 打开，都无法载入，界面上无提示 文件夹名称 `yuuhui玉汇 - 圣女の史莱姆修行计划 [106P1.53GB]`
> 
> **Screenshots** console 报错如下 ![image](https://private-user-images.githubusercontent.com/39426660/302358045-0f90bdf4-a412-422a-9882-c00390846bda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODk3MDEsIm5iZiI6MTcwNzE4OTQwMSwicGF0aCI6Ii8zOTQyNjY2MC8zMDIzNTgwNDUtMGY5MGJkZjQtYTQxMi00MjJhLTk4ODItYzAwMzkwODQ2YmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAzMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNjczYzE2OWFiMmFmMjk5ODEwMWNmZGQ0ZTdiZGYxYWRmNDIxZDZhNzgwNDY3NTY5MTZlZmMyYjUwMDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_R4Q4Z0rzbNorRW6jkeyXXtiUZSpJofwlbHbtYeBsA)
> 
> 图片基本信息如下 ![image](https://private-user-images.githubusercontent.com/39426660/302359235-33f289dc-13e5-48b5-935e-04f85f787456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODk3MDEsIm5iZiI6MTcwNzE4OTQwMSwicGF0aCI6Ii8zOTQyNjY2MC8zMDIzNTkyMzUtMzNmMjg5ZGMtMTNlNS00OGI1LTkzNWUtMDRmODVmNzg3NDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAzMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMWNhNzIyY2E4MjgyZDQ3ZDljN2RlMjk0ZWY0YWU5NGRmODBlZjQzMjAwMWUzNTRiODNkMjc3YmJiNTQ0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RoP6KaOs0hJlZCn7kuL0o69LhycnN1rIG2LbQi2S6h0)
> 
> **Additional context** Add any other context about the problem here.

已经确定文件夹载入算法有问题，回头修复，你暂时可以去掉文件夹中特殊字符使用，谢谢~

**Comment by ChenDY2233** [comment]
好的

**Comment by Edge-coordinates** [comment]
已修复该问题，请更新，如果还有问题的话，请继续反馈，谢谢。

**Comment by Edge-coordinates** [comment]
已修复该问题，请更新，如果还有问题的话，请继续反馈，谢谢。
